console.log("Daite rabotu(")
console.log("Daite rabotu(")
console.log("Daite rabotu(")
console.log("Daite rabotu(")
console.log("Daite rabotu(")
console.log("Daite rabotu(")
console.log("Daite rabotu(")

console.log("Daite rabotu(")
console.log("Daite rabotu(")
console.log("Daite rabotu(")
console.log("Daite rabotu(")
console.log("Daite rabotu(")
console.log("Daite rabotu(")
console.log("Daite rabotu(")
